using System;
using System.IO;

namespace DataForge;

internal static class GeneratedArtifactWriter
{
    internal static string GeneratedHeader(string domainName, string overrideFileName, string label)
    {
        return
            $"# Generated by {DataForgePlugin.ModName}: {domainName} {label}." + Environment.NewLine +
            $"# Do not edit this generated file directly. Copy entries into {overrideFileName} or {OverrideWildcard(overrideFileName)}." + Environment.NewLine;
    }

    internal static bool TryWriteFullScaffold(string path, string domainName, Func<string> buildContent, out string error)
    {
        error = "";
        try
        {
            WriteTextIfChanged(path, buildContent());
            DataForgePlugin.Log.LogInfo($"Wrote {domainName} full scaffold to {path}.");
            return true;
        }
        catch (Exception ex)
        {
            error = ex.Message;
            return false;
        }
    }

    internal static bool TryWriteFullScaffoldIfReady(
        string path,
        string domainName,
        bool isReady,
        string notReadyError,
        Func<string> buildContent,
        out string error)
    {
        if (!isReady)
        {
            error = notReadyError;
            return false;
        }

        return TryWriteFullScaffold(path, domainName, buildContent, out error);
    }

    internal static bool WriteReference(
        string directory,
        string referenceFileName,
        string domainName,
        string overrideFileName,
        string content)
    {
        return WriteTextIfChanged(
            Path.Combine(directory, referenceFileName),
            GeneratedHeader(domainName, overrideFileName, "compact lookup") + content);
    }

    internal static bool WriteReferenceIfReady(
        bool isReady,
        string directory,
        string referenceFileName,
        string domainName,
        string overrideFileName,
        Func<string> buildContent)
    {
        if (!isReady)
        {
            return false;
        }

        return WriteReference(directory, referenceFileName, domainName, overrideFileName, buildContent());
    }

    internal static bool WriteTextIfChanged(string path, string content)
    {
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        content ??= "";
        if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
        {
            return false;
        }

        File.WriteAllText(path, content);
        return true;
    }

    private static string OverrideWildcard(string overrideFileName)
    {
        string extension = Path.GetExtension(overrideFileName);
        string baseName = Path.GetFileNameWithoutExtension(overrideFileName);
        return $"{baseName}_*{extension}";
    }
}
