using System;
using System.IO;

namespace DataForge;

internal static class GeneratedArtifactWriter
{
    internal static bool CanWriteGeneratedArtifact(bool isReady, string notReadyError, out string error)
    {
        if (!DataForgePlugin.UsesLocalAuthorityFiles)
        {
            error = "DataForge generated files can only be written by the local source-of-truth host.";
            return false;
        }

        if (DataForgeWorldLifecycle.IsShuttingDown)
        {
            error = "DataForge generated files cannot be written while the world is shutting down.";
            return false;
        }

        if (!isReady)
        {
            error = notReadyError;
            return false;
        }

        error = "";
        return true;
    }

    internal static string GeneratedHeader(string domainName, string overrideFileName, string label)
    {
        return
            $"# Generated by {DataForgePlugin.ModName}: {domainName} {label}." + Environment.NewLine +
            $"# Do not edit this generated file directly. Copy entries into {overrideFileName} or {OverrideWildcard(overrideFileName)}." + Environment.NewLine;
    }

    internal static bool TryWriteFullScaffold(string path, string domainName, Func<string> buildContent, out string error)
    {
        error = "";
        try
        {
            WriteTextIfChanged(path, buildContent());
            DataForgePlugin.Log.LogInfo($"Wrote {domainName} full scaffold to {path}.");
            return true;
        }
        catch (Exception ex)
        {
            error = ex.Message;
            return false;
        }
    }

    internal static bool TryWriteFullScaffoldIfReady(
        string path,
        string domainName,
        bool isReady,
        string notReadyError,
        Func<string> buildContent,
        out string error)
    {
        if (!CanWriteGeneratedArtifact(isReady, notReadyError, out error))
        {
            return false;
        }

        return TryWriteFullScaffold(path, domainName, buildContent, out error);
    }

    internal static bool TryWriteReferenceIfReady(
        string path,
        string domainName,
        string overrideFileName,
        bool isReady,
        string notReadyError,
        Func<string?> buildContent,
        out bool changed,
        out string error)
    {
        changed = false;
        if (!CanWriteGeneratedArtifact(isReady, notReadyError, out error))
        {
            return false;
        }

        try
        {
            string? content = buildContent();
            if (content == null)
            {
                error = $"No {domainName} game data is available for the reference file.";
                return false;
            }

            changed = WriteTextIfChanged(
                path,
                GeneratedHeader(domainName, overrideFileName, "compact lookup") + content);
            error = "";
            return true;
        }
        catch (Exception ex)
        {
            error = $"Could not regenerate the {domainName} reference file: {ex.Message}";
            return false;
        }
    }

    internal static bool WriteTextIfChanged(string path, string content)
    {
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        content ??= "";
        if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
        {
            return false;
        }

        File.WriteAllText(path, content);
        return true;
    }

    private static string OverrideWildcard(string overrideFileName)
    {
        string extension = Path.GetExtension(overrideFileName);
        string baseName = Path.GetFileNameWithoutExtension(overrideFileName);
        return $"{baseName}_*{extension}";
    }
}
