<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ValheimGamePath Condition="'$(ValheimGamePath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimGamePath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil"><HintPath>$(ValheimGamePath)\BepInEx\core\Mono.Cecil.dll</HintPath></Reference>
    <Reference Include="0Harmony"><HintPath>$(ValheimGamePath)\BepInEx\core\0Harmony.dll</HintPath></Reference>
  </ItemGroup>
</Project>
